[versions]
application = "8.13.1"
kotlin = "2.2.21"
compose-bom = "2025.11.00"
datastore = "1.1.7"
navigation = "2.7.7" # 2.8.0 introduces type safety for destinations
room = "2.8.3"
work-runtime-ktx = "2.11.0"
firebase-bom = "34.5.0"
google-devtools-ksp = "2.2.0-2.0.2"
google-services = "4.4.4"
squareup-moshi = "1.15.2"
squareup-retrofit2 = "3.0.0"

[libraries]
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling"}
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-runtime-ktx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "squareup-moshi" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "squareup-retrofit2" }

[plugins]
application = { id = "com.android.application", version.ref = "application" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
room = { id = "androidx.room", version.ref = "room" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "google-devtools-ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
